name: "重构代码"
task_type: "refactor"
description: "改进代码质量、可读性或性能而不改变功能"

triggers:
  - 重构
  - 优化
  - 改进
  - refactor
  - optimize
  - improve
  - cleanup
  - modernize

checklist:
  - 确保有完整的测试覆盖
  - 小步进行重构，每次一个小改动
  - 每步修改后运行测试验证功能未变
  - 避免同时进行多个重构
  - 保持API和接口稳定
  - 移除死代码和不使用的导入
  - 更新相关的文档和注释
  - 性能基准测试验证改进

best_practices:
  python:
    - 使用工具如autopep8、black格式化代码
    - 提取重复代码到函数
    - 使用更合适的数据结构
    - 简化复杂的条件逻辑
    - 移除过时的兼容性代码
    - 使用现代Python特性
    - 重构时保持向后兼容

  javascript:
    - 使用Prettier格式化代码
    - 提取复杂逻辑为独立函数
    - 使用更现代的语法（箭头函数、解构等）
    - 简化嵌套回调或Promise链
    - 移除不使用的变量
    - 考虑使用TypeScript
    - 优化import/export语句

  java:
    - 应用SOLID原则
    - 提取方法消除重复
    - 使用更合适的设计模式
    - 移除过时的API调用
    - 优化异常处理
    - 考虑使用stream API
    - 改进变量和方法命名

  go:
    - 简化错误处理链
    - 使用接口提高灵活性
    - 消除嵌套提高可读性
    - 优化内存分配
    - 使用标准库而非自定义实现
    - 改进函数签名的清晰度

common_pitfalls:
  - 同时进行多个重构导致难以定位问题
  - 重构过程中引入功能改变
  - 忽视测试验证导致功能破坏
  - 过度工程化或过度简化
  - 在重构时改动API导致兼容性问题
  - 没有文档说明重构的原因和好处

acceptance_criteria:
  - 所有现有测试通过
  - 代码可读性明显提升
  - 性能指标达到目标
  - API保持兼容
  - 通过代码审查
  - 文档已更新

examples:
  - "优化数据库查询性能"
  - "重构大型类拆分为多个小类"
  - "改进错误处理机制"
