name: "代码审查"
task_type: "review"
description: "进行代码审查、代码检查或设计评审"

triggers:
  - 审查
  - 检查
  - 评审
  - review
  - check
  - inspect
  - audit
  - validation

checklist:
  - 检查代码是否符合需求和设计文档
  - 验证功能正确性和边界情况处理
  - 评估代码可读性和维护性
  - 检查测试覆盖率是否充分
  - 审视性能影响和瓶颈
  - 评估安全性和潜在漏洞
  - 检查是否遵循编码规范
  - 评估是否有更好的实现方案

best_practices:
  python:
    - 检查遵循PEP 8规范
    - 验证类型注解完整
    - 查看docstring是否清晰
    - 评估异常处理是否完善
    - 检查是否有潜在的资源泄漏
    - 查看是否使用了过时的API
    - 建议使用更Pythonic的写法

  javascript:
    - 检查遵循ESLint规则
    - 验证Promise处理是否正确
    - 查看是否有内存泄漏风险
    - 评估异步代码的正确性
    - 检查是否有XSS或注入风险
    - 查看类型定义是否完整（TypeScript）
    - 建议改进变量命名

  java:
    - 检查遵循Java命名规范
    - 验证异常处理是否合理
    - 评估类设计是否遵循SOLID原则
    - 检查是否有潜在的并发问题
    - 查看资源是否正确关闭
    - 评估性能和内存使用
    - 建议使用更恰当的设计模式

  go:
    - 检查错误处理是否完善
    - 验证是否避免了goroutine泄漏
    - 评估接口设计是否合理
    - 检查是否有资源泄漏
    - 查看性能和内存分配
    - 评估代码的可测试性
    - 建议改进代码清晰度

common_pitfalls:
  - 审查过于关注代码风格而忽视逻辑问题
  - 给出具体化的批评而非建设性反馈
  - 审查范围过大导致容易遗漏问题
  - 没有关注性能和安全性
  - 对代码作者的建议缺乏同理心
  - 没有验证自己的建议是否可行
  - 审查太快导致遗漏关键问题

acceptance_criteria:
  - 代码审查意见具体清晰
  - 所有关键问题都已指出
  - 反馈建设性且可操作
  - 验证了安全性和性能
  - 检查了测试覆盖率
  - 审查意见已记录
  - 代码作者的所有问题都得到解答

examples:
  - "审查新增的用户管理模块"
  - "检查性能优化代码的正确性"
  - "评审新的API设计和实现"
